"""
SDF Code Executor
Safely executes SDF code generated by LLM
"""

import numpy as np
from typing import Callable, Optional
import tempfile
import os


class SDFExecutor:
    """Executes SDF code and returns the SDF function"""
    
    def __init__(self):
        """Initialize SDF executor"""
        self.last_function = None
        self.error_message = None
    
    def execute_code(self, code: str) -> Optional[Callable]:
        """
        Execute SDF code and extract the 'f' function
        
        Args:
            code: Python code using sdf library
            
        Returns:
            The 'f' function object, or None if execution failed
        """
        try:
            # Create local namespace for execution
            local_vars = {}
            
            # First attempt: execute as-is
            try:
                exec(code, {"__builtins__": __builtins__, "np": np}, local_vars)
            except TypeError as te:
                # If error is about missing arguments, try fixing common cases
                if "missing" in str(te) and "argument" in str(te):
                    # Try to auto-fix common missing parameters
                    fixed_code = self._fix_missing_parameters(code)
                    if fixed_code != code:
                        exec(fixed_code, {"__builtins__": __builtins__, "np": np}, local_vars)
                    else:
                        raise
                else:
                    raise
            
            # Extract the 'f' variable
            if "f" in local_vars:
                self.last_function = local_vars["f"]
                self.error_message = None
                return self.last_function
            else:
                self.error_message = "No 'f' variable defined in SDF code"
                return None
                
        except Exception as e:
            self.error_message = f"Error executing SDF code: {str(e)}"
            print(self.error_message)
            return None
    
    def _fix_missing_parameters(self, code: str) -> str:
        """
        Try to fix common SDF function calls with missing parameters
        
        Args:
            code: Original SDF code
            
        Returns:
            Fixed code, or original if no fix found
        """
        import re
        
        fixed = code
        
        # Fix common shapes with missing parameters
        fixes = {
            r'\bpyramid\(\)': 'pyramid(2)',
            r'\bsphere\(\)': 'sphere(1)',
            r'\bbox\(\)': 'box(1)',
            r'\bcylinder\(\)': 'cylinder(0.5)',
            r'\bcone\(\)': 'capped_cone(-Z, Z, 1, 0.5)',
            r'\btorus\(\)': 'torus(1, 0.25)',
            r'\bcapsule\(\)': 'capsule(-Z, Z, 0.5)',
            r'\bellipsoid\(\)': 'ellipsoid((1,1,1))',
        }
        
        for pattern, replacement in fixes.items():
            fixed = re.sub(pattern, replacement, fixed)
        
        return fixed
    
    def execute_from_file(self, filepath: str) -> Optional[Callable]:
        """
        Execute SDF code from a file
        
        Args:
            filepath: Path to Python file
            
        Returns:
            The 'f' function object, or None if execution failed
        """
        try:
            with open(filepath, 'r') as f:
                code = f.read()
            return self.execute_code(code)
        except Exception as e:
            self.error_message = f"Error reading file: {str(e)}"
            return None
    
    def create_sdf_function(self, code: str) -> Optional[Callable]:
        """
        Execute code and return SDF evaluation function
        
        Args:
            code: Python code defining 'f'
            
        Returns:
            Function that evaluates SDF values
        """
        sdf_obj = self.execute_code(code)
        if sdf_obj is None:
            return None
        
        # Return a callable that evaluates the SDF
        def evaluate_sdf(points: np.ndarray) -> np.ndarray:
            """
            Evaluate SDF at given points
            
            Args:
                points: Array of shape (N, 3)
                
            Returns:
                Array of shape (N,) with SDF values
            """
            try:
                result = sdf_obj(points)
                return result
            except Exception as e:
                raise RuntimeError(f"Error evaluating SDF: {str(e)}")
        
        return evaluate_sdf
    
    def get_error_message(self) -> Optional[str]:
        """Get last error message"""
        return self.error_message


# Example usage
if __name__ == "__main__":
    executor = SDFExecutor()
    
    # Test code
    test_code = """
from sdf import sphere, box
f = sphere(2) & box(3)
"""
    
    result = executor.execute_code(test_code)
    print("Execution result:", result)
    print("Error message:", executor.get_error_message())
    
    if result:
        # Create SDF function
        sdf_func = executor.create_sdf_function(test_code)
        
        # Test evaluation
        test_points = np.array([[0, 0, 0], [1, 1, 1], [3, 3, 3]])
        values = sdf_func(test_points)
        print("SDF values at test points:", values)
